name: cake_order
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  eva_icons_flutter: ^2.0.1
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flutter_secure_storage: ^3.3.5
  font_awesome_flutter: ^8.10.0
  geocoder: ^0.2.1
  geolocator: ^6.1.6
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.6
  page_transition: ^1.1.7+2
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  assets:
    - images/Splash_cake.svg

  uses-material-design: true
 
